const motivationalPhrases = [
  "Uma hora nova, uma nova chance!",
  "Hora de pensar positivo!",
  "Cada minuto conta!",
  "Faça valer esta hora!",
  "Aproveite o momento!",
  "Você está indo muito bem!",
  "Siga em frente e não olhe para trás!",
  "O sucesso é a soma de pequenos esforços repetidos diariamente.",
  "Acredite em si mesmo e tudo será possível.",
  "Não deixe que o medo de falhar impeça você de tentar.",
  "A força de vontade é o que transforma sonhos em realidade.",
  "Cada passo para frente é um passo na direção certa.",
  "Grandes conquistas começam com pequenas ações.",
  "O segredo do sucesso é começar antes de estar pronto.",
  "A persistência é o caminho do êxito.",
  "Você é mais forte do que pensa.",
  "O sucesso é a soma de pequenos esforços.",
  "Tenha coragem para seguir seus sonhos.",
  "Cada nova manhã traz uma nova oportunidade.",
  "Acredite que você pode, e você estará no meio do caminho.",
  "O único limite é aquele que você impõe a si mesmo.",
  "A jornada de mil milhas começa com um único passo.",
  "A motivação te faz começar, o hábito te faz continuar.",
  "Não espere o momento perfeito, faça o momento perfeito.",
  "O sucesso é a soma de pequenas vitórias diárias.",
  "Acredite no processo e continue se esforçando.",
  "O poder da mente é infinito.",
  "Você tem a capacidade de superar qualquer desafio.",
  "O sucesso é o resultado da preparação, trabalho duro e aprendizado com os fracassos.",
  "A disciplina é a ponte entre metas e realizações.",
  "Encare cada obstáculo como uma oportunidade de crescimento.",
  "Você é capaz de realizar coisas incríveis.",
  "O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
  "Você é a única pessoa que pode limitar sua grandeza.",
  "O sucesso é alcançado e mantido por aqueles que continuam tentando.",
  "O sucesso é a habilidade de ir de fracasso em fracasso sem perder o entusiasmo.",
  "Você é o criador do seu próprio destino.",
  "O fracasso é apenas uma oportunidade para recomeçar com mais inteligência.",
  "Não há segredo para o sucesso, é o resultado da preparação e trabalho árduo.",
  "Você é capaz de coisas incríveis.",
  "A chave para o sucesso é acreditar em si mesmo.",
  "O sucesso é um caminho construído com passos pequenos e constantes.",
  "Você está a um passo de realizar seus sonhos.",
  "A ação é a chave fundamental para todo sucesso.",
  "Nunca subestime o poder de um pequeno ato de bondade.",
  "Você é mais forte do que pensa.",
  "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
  "Você tem tudo o que precisa para alcançar o sucesso.",
  "O sucesso é resultado de um trabalho duro e constante.",
  "O sucesso é uma jornada, não um destino.",
  "Você é o autor da sua própria história de sucesso.",
  "O sucesso começa com a disposição de tentar.",
  "O sucesso não é a chave para a felicidade, a felicidade é a chave para o sucesso.",
  "Cada dia é uma nova oportunidade para alcançar seus objetivos.",
  "Você é capaz de alcançar coisas extraordinárias.",
  "O sucesso é construído com pequenas vitórias diárias.",
  "Você tem o poder de mudar sua vida para melhor.",
  "O sucesso é o resultado da perseverança.",
  "O sucesso é uma jornada, não um destino.",
  "Você é a única pessoa que pode fazer seus sonhos se tornarem realidade.",
  "O sucesso é alcançado por aqueles que continuam tentando.",
  "Você é mais capaz do que imagina.",
  "O sucesso vem para aqueles que nunca desistem.",
  "Você é mais forte do que qualquer desafio.",
  "O sucesso é o resultado de um trabalho bem feito.",
  "Você tem a capacidade de realizar coisas incríveis.",
  "O sucesso é a soma de pequenos esforços diários.",
  "Você é o criador do seu próprio sucesso.",
  "O sucesso é construído com pequenas vitórias ao longo do caminho.",
  "Você tem o poder de mudar sua vida para melhor.",
  "O sucesso é uma jornada contínua.",
  "Você é a única pessoa que pode limitar sua grandeza.",
  "O sucesso é alcançado por aqueles que nunca desistem.",
  "Você é mais forte do que qualquer desafio.",
  "O sucesso é resultado de um trabalho bem feito.",
  "Você tem o poder de mudar sua vida para melhor.",
  "O sucesso é a soma de pequenos esforços.",
  "Você é o autor da sua própria história de sucesso.",
  "O sucesso é construído com pequenas vitórias diárias.",
  "Você tem a capacidade de realizar coisas extraordinárias.",
  "O sucesso é alcançado por aqueles que continuam tentando.",
  "Você é mais forte do que pensa.",
  "O sucesso é uma jornada, não um destino.",
  "Você tem tudo o que precisa para alcançar o sucesso.",
  "O sucesso é construído com esforço e dedicação.",
  "Você é capaz de alcançar seus objetivos.",
  "O sucesso começa com a disposição de tentar.",
  "Você é mais forte do que qualquer desafio.",
  "O sucesso é construído com pequenas vitórias ao longo do caminho.",
  "Você é o criador do seu próprio destino.",
];

const jokes = [
  "Hora de uma piada: O que é um pontinho vermelho no canto da sala? Uma pimenta do reino exploradora!",
  "Por que o computador foi ao médico? Porque ele tinha um vírus!",
  "O que o tomate foi fazer no banco? Tirar extrato!",
  "Qual é o peixe mais inteligente? O atum!",
  "Por que a aranha é um animal de sucesso? Porque ela trabalha na web!",
  "Qual é a diferença entre uma pizza e um músico? A pizza pode alimentar uma família de quatro pessoas.",
  "Por que o policial não pegou o ladrão de pizza? Porque ele estava sempre um passo à frente.",
  "Como se chama um boi que toca bateria? Um boi-lão!",
  "Por que o elefante não usa computador? Porque tem medo do mouse.",
  "Qual é a piada favorita do marceneiro? Serra que cola!",
  "O que o zero disse para o oito? Adorei seu cinto!",
  "Por que a bicicleta não conseguiu se levantar? Porque estava sem pneu.",
  "Por que o espelho se envergonhou? Porque ele estava refletindo demais.",
  "Por que o caderno estava deprimido? Porque ele tinha muitas páginas em branco.",
  "Qual é o cúmulo do desleixo? Não saber onde está o fio da meada.",
  "Por que o tomate não foi ao banco? Porque ele estava com medo de ser amassado.",
  "O que a impressora disse para o papel? Pare de me enrolar!",
  "Por que a vaca não usa gravata? Porque ela tem um colarinho naturalmente elegante.",
  "O que o pato falou para a pata? Vem cá, minha pata!",
  "Por que o balde foi promovido? Porque ele sempre estava cheio de ideias!",
  "O que a ovelha disse para a outra? Você está pronta para ser tosquiada?",
  "Por que o cachorro foi para a escola? Para aprender a latir em outra língua.",
  "Por que o pássaro não foi ao médico? Porque ele estava se sentindo voando!",
  "O que o lápis disse para o caderno? Vou te dar um ponto final.",
  "Por que a lâmpada foi promovida? Porque ela sempre estava brilhando!",
  "O que a chave disse para a fechadura? Estamos trancados em um caso de amor.",
  "Por que o relógio estava sempre de bom humor? Porque ele tinha tempo de sobra!",
  "O que o papel disse para a caneta? Escreva-me algo bonito.",
  "Por que o lápis foi ao médico? Porque ele estava com grafite no coração.",
  "Qual é o contrário de volátil? Volastável!",
  "O que o termômetro disse para o médico? Estou subindo na vida!",
  "Por que o macarrão não vai ao banco? Porque ele não quer ser enrolado.",
  "O que o pão disse para a manteiga? Você me derrete!",
  "Por que a máquina de lavar estava de mau humor? Porque estava cheia de roupas sujas.",
  "O que o chinelo disse para o pé? Eu estou aos seus pés!",
  "Por que o lápis era ruim de piadas? Porque ele sempre apagava o final.",
  "O que a nota musical disse para a partitura? Estamos em sintonia.",
  "Por que o feijão estava triste? Porque ele estava se sentindo esmagado.",
  "O que o calendário disse para o relógio? Estamos sempre juntos, mas nunca ao mesmo tempo.",
  "Por que o chocolate foi ao terapeuta? Porque ele estava derretendo de stress.",
  "O que a luva disse para a mão? Estamos juntos nessa!",
  "Por que o guarda-chuva não compartilhou seu segredo? Porque era confidencial.",
  "O que o celular disse para o carregador? Você me completa.",
  "Por que a faca não brigou com o garfo? Porque eles já tinham pontos de vista afiados.",
  "O que o caderno disse para a caneta? Estamos escrevendo nossa história juntos.",
  "Por que o gato não foi ao cinema? Porque ele estava com medo de levar uma patada.",
  "O que o pinguim disse para a geladeira? Estamos juntos no frio!",
  "Por que o sapato foi ao terapeuta? Porque ele estava desgastado.",
  "O que a toalha disse para a água? Eu estou pronta para absorver tudo!",
  "Por que o livro de matemática estava triste? Porque ele tinha muitos problemas.",
  "O que a chave disse para o cadeado? Estamos presos juntos!",
  "Por que o quadro estava sempre em evidência? Porque ele era o centro das atenções.",
  "O que o lápis disse para o apontador? Você me deixa mais afiado!",
  "Por que o armário não participou da festa? Porque ele estava trancado em si mesmo.",
  "O que a cadeira disse para a mesa? Estamos sentados no mesmo barco.",
  "Por que a cortina foi ao terapeuta? Porque ela estava pendurada nos mesmos problemas.",
  "O que o sorvete disse para a colher? Você me derrete de amor.",
  "Por que a melancia não foi ao médico? Porque ela estava cheia de sementes de esperança.",
  "O que o travesseiro disse para o lençol? Estamos juntos nos sonhos!",
  "Por que a parede foi ao terapeuta? Porque ela estava se sentindo pressionada.",
  "O que o ventilador disse para o calor? Eu vou soprar você para longe.",
  "Por que o relógio não brigou com o tempo? Porque eles estavam em sincronia.",
  "O que a maçaneta disse para a porta? Vamos abrir juntos para novas oportunidades!",
  "Por que a chave de fenda foi promovida? Porque ela sempre girava as situações a seu favor.",
  "O que a janela disse para a cortina? Estamos juntos nessa visão.",
  "Por que o violão foi ao médico? Porque ele estava com cordas soltas.",
  "O que a faca disse para a tábua de corte? Estamos em uma missão afiada juntos.",
  "Por que a garrafa de água estava sempre tranquila? Porque ela estava cheia de serenidade.",
  "O que o lápis disse para a borracha? Eu cometo erros, mas você me corrige.",
  "Por que o biscoito não foi ao terapeuta? Porque ele já estava quebrado.",
  "O que o telefone disse para o fone de ouvido? Estamos sempre em contato!",
  "Por que o patinete estava sempre animado? Porque ele adorava dar voltas.",
  "O que o café disse para a xícara? Eu sou seu motivo para acordar.",
  "Por que o papel higiênico não brigou com o rolo? Porque eles estavam sempre em sintonia.",
  "O que o chaveiro disse para as chaves? Estamos todos juntos na bagunça!",
];

const creativePhrases = [
  "Aproveite esta pausa!",
  "Sorria, alguém pensa em você!",
  "Hora de uma nova ideia!",
  "Quem não arrisca, não petisca!",
  "As melhores ideias surgem nas horas mais inesperadas!",
  "Seja a mudança que você quer ver no mundo!",
  "Pense fora da caixinha!",
  "Deixe sua criatividade voar alto!",
  "Tudo o que você precisa está dentro de você.",
  "Transforme suas ideias em realidade.",
  "Explore o desconhecido e descubra novas possibilidades.",
  "A inspiração está ao seu redor.",
  "Dê asas à sua imaginação.",
  "O impossível é apenas o que ainda não foi tentado.",
  "Cada dia é uma nova oportunidade para criar.",
  "Você é o arquiteto dos seus sonhos.",
  "A criatividade é a inteligência se divertindo.",
  "Pinte sua vida com as cores dos seus sonhos.",
  "A arte de criar é a arte de viver.",
  "Deixe sua marca no mundo.",
  "O mundo é o seu palco, brilhe!",
  "Seja ousado, seja criativo.",
  "A inovação começa com uma ideia simples.",
  "Transforme problemas em oportunidades criativas.",
  "A magia acontece quando você acredita.",
  "Crie algo que inspire os outros.",
  "Deixe sua criatividade fluir livremente.",
  "Acredite na sua capacidade de criar algo incrível.",
  "O mundo é cheio de possibilidades, explore-as!",
  "Cada ideia é uma nova aventura.",
  "Desafie-se a pensar de maneira diferente.",
  "A imaginação é o início de todas as realizações.",
  "A criatividade não tem limites.",
  "Pense grande, sonhe alto.",
  "A arte de criar é a arte de ser único.",
  "Inspire-se e inspire os outros.",
  "O futuro pertence aos criativos.",
  "A criatividade é a chave para o sucesso.",
  "Seja a mudança que você deseja ver no mundo.",
  "Crie o que você deseja ver no mundo.",
  "A inovação nasce da curiosidade.",
  "Acredite na sua capacidade de fazer a diferença.",
  "Pinte o mundo com as cores dos seus sonhos.",
  "O poder da criatividade está nas suas mãos.",
  "Crie algo que seja digno de ser lembrado.",
  "A criatividade é a linguagem universal.",
  "O mundo precisa da sua criatividade.",
  "A imaginação é o único limite.",
  "Crie o seu próprio caminho.",
  "A criatividade é a alma da inovação.",
  "Seja criativo em tudo o que você faz.",
  "A imaginação é o primeiro passo para a criação.",
  "O poder da criatividade é ilimitado.",
  "Crie o que faz seu coração cantar.",
  "A criatividade é o segredo do sucesso.",
  "Transforme ideias em ações.",
  "A arte de criar é a arte de se expressar.",
  "A imaginação é a janela para o futuro.",
  "A criatividade é a chama que acende a inovação.",
  "O mundo precisa da sua visão única.",
  "Seja corajoso o suficiente para ser criativo.",
  "Crie algo que traga alegria ao mundo.",
  "A imaginação é o combustível da criatividade.",
  "A criatividade é a chave para a mudança.",
  "Pinte o mundo com a paleta dos seus sonhos.",
  "Acredite na sua capacidade de transformar o mundo.",
  "A criatividade é a essência da inovação.",
  "Crie algo que inspire os outros a sonhar.",
  "A imaginação é o início de toda criação.",
  "A criatividade é a chave para a felicidade.",
  "Acredite no poder da sua imaginação.",
  "Crie o que faz o seu coração bater mais forte.",
  "A arte de criar é a arte de viver com paixão.",
  "Pense fora da caixa e crie algo extraordinário.",
  "A criatividade é a chave para o futuro.",
  "Crie algo que faça o mundo sorrir.",
  "A imaginação é o combustível da inovação.",
  "A criatividade é a chave para a realização pessoal.",
  "Acredite na sua capacidade de criar o impossível.",
  "Pinte a vida com as cores da sua imaginação.",
  "A arte de criar é a arte de transformar sonhos em realidade.",
  "Crie algo que toque o coração das pessoas.",
  "A criatividade é a chave para a verdadeira felicidade.",
  "Seja ousado o suficiente para ser criativo.",
  "Crie algo que inspire os outros a seguir seus sonhos.",
  "A imaginação é o primeiro passo para a grandeza.",
  "A criatividade é o motor da mudança.",
  "Pinte o mundo com a sua visão única.",
  "Acredite na sua capacidade de transformar o mundo para melhor.",
  "A criatividade é a chave para o sucesso duradouro.",
];

export function getRandomPhrase() {
  const currentHour = new Date().getHours();

  if (currentHour % 3 === 0) {
    return motivationalPhrases[
      Math.floor(Math.random() * motivationalPhrases.length)
    ];
  } else if (currentHour % 3 === 1) {
    return jokes[Math.floor(Math.random() * jokes.length)];
  } else {
    return creativePhrases[Math.floor(Math.random() * creativePhrases.length)];
  }
}
