const motivationalPhrases = [
  "Uma hora nova, uma nova chance!",
  "Hora de pensar positivo!",
  "Cada minuto conta!",
  "Faça valer esta hora!",
  "Aproveite o momento!",
  "Você está indo muito bem!",
  "Siga em frente e não olhe para trás!",
  "O sucesso é a soma de pequenos esforços repetidos diariamente.",
  "Acredite em si mesmo e tudo será possível.",
  "Não deixe que o medo de falhar impeça você de tentar.",
  "A força de vontade é o que transforma sonhos em realidade.",
  "Cada passo para frente é um passo na direção certa.",
  "Grandes conquistas começam com pequenas ações.",
  "O segredo do sucesso é começar antes de estar pronto.",
  "A persistência é o caminho do êxito.",
  "Você é mais forte do que pensa.",
  "O sucesso é a soma de pequenos esforços.",
  "Tenha coragem para seguir seus sonhos.",
  "Cada nova manhã traz uma nova oportunidade.",
  "Acredite que você pode, e você estará no meio do caminho.",
  "O único limite é aquele que você impõe a si mesmo.",
  "A jornada de mil milhas começa com um único passo.",
  "A motivação te faz começar, o hábito te faz continuar.",
  "Não espere o momento perfeito, faça o momento perfeito.",
  "O sucesso é a soma de pequenas vitórias diárias.",
  "Acredite no processo e continue se esforçando.",
  "O poder da mente é infinito.",
  "Você tem a capacidade de superar qualquer desafio.",
  "O sucesso é o resultado da preparação, trabalho duro e aprendizado com os fracassos.",
  "A disciplina é a ponte entre metas e realizações.",
  "Encare cada obstáculo como uma oportunidade de crescimento.",
  "Você é capaz de realizar coisas incríveis.",
  "O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
  "Você é a única pessoa que pode limitar sua grandeza.",
  "O sucesso é alcançado e mantido por aqueles que continuam tentando.",
  "O sucesso é a habilidade de ir de fracasso em fracasso sem perder o entusiasmo.",
  "Você é o criador do seu próprio destino.",
  "O fracasso é apenas uma oportunidade para recomeçar com mais inteligência.",
  "Não há segredo para o sucesso, é o resultado da preparação e trabalho árduo.",
  "Você é capaz de coisas incríveis.",
  "A chave para o sucesso é acreditar em si mesmo.",
  "O sucesso é um caminho construído com passos pequenos e constantes.",
  "Você está a um passo de realizar seus sonhos.",
  "A ação é a chave fundamental para todo sucesso.",
  "Nunca subestime o poder de um pequeno ato de bondade.",
  "Você é mais forte do que pensa.",
  "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
  "Você tem tudo o que precisa para alcançar o sucesso.",
  "O sucesso é resultado de um trabalho duro e constante.",
  "O sucesso é uma jornada, não um destino.",
  "Você é o autor da sua própria história de sucesso.",
  "O sucesso começa com a disposição de tentar.",
  "O sucesso não é a chave para a felicidade, a felicidade é a chave para o sucesso.",
  "Cada dia é uma nova oportunidade para alcançar seus objetivos.",
  "Você é capaz de alcançar coisas extraordinárias.",
  "O sucesso é construído com pequenas vitórias diárias.",
  "Você tem o poder de mudar sua vida para melhor.",
  "O sucesso é o resultado da perseverança.",
  "O sucesso é uma jornada, não um destino.",
  "Você é a única pessoa que pode fazer seus sonhos se tornarem realidade.",
  "O sucesso é alcançado por aqueles que continuam tentando.",
  "Você é mais capaz do que imagina.",
  "O sucesso vem para aqueles que nunca desistem.",
  "Você é mais forte do que qualquer desafio.",
  "O sucesso é o resultado de um trabalho bem feito.",
  "Você tem a capacidade de realizar coisas incríveis.",
  "O sucesso é a soma de pequenos esforços diários.",
  "Você é o criador do seu próprio sucesso.",
  "O sucesso é construído com pequenas vitórias ao longo do caminho.",
  "Você tem o poder de mudar sua vida para melhor.",
  "O sucesso é uma jornada contínua.",
  "Você é a única pessoa que pode limitar sua grandeza.",
  "O sucesso é alcançado por aqueles que nunca desistem.",
  "Você é mais forte do que qualquer desafio.",
  "O sucesso é resultado de um trabalho bem feito.",
  "Você tem o poder de mudar sua vida para melhor.",
  "O sucesso é a soma de pequenos esforços.",
  "Você é o autor da sua própria história de sucesso.",
  "O sucesso é construído com pequenas vitórias diárias.",
  "Você tem a capacidade de realizar coisas extraordinárias.",
  "O sucesso é alcançado por aqueles que continuam tentando.",
  "Você é mais forte do que pensa.",
  "O sucesso é uma jornada, não um destino.",
  "Você tem tudo o que precisa para alcançar o sucesso.",
  "O sucesso é construído com esforço e dedicação.",
  "Você é capaz de alcançar seus objetivos.",
  "O sucesso começa com a disposição de tentar.",
  "Você é mais forte do que qualquer desafio.",
  "O sucesso é construído com pequenas vitórias ao longo do caminho.",
  "Você é o criador do seu próprio destino.",
];

const jokes = [
  "Por que a pimenta do reino viajou pelo mundo? Para apimentar novas histórias!",
  "Por que o computador resolveu tirar férias? Ele precisava de um descanso do byte a byte.",
  "O que o tomate fez ao encontrar seu reflexo? Tirou um extrato de si mesmo!",
  "Qual é o peixe que nunca se dá mal? O atum, porque está sempre na lata!",
  "Por que a aranha é uma ótima programadora? Porque ela é uma mestre na teia!",
  "O que uma orquestra e uma pizza têm em comum? Ambas precisam de harmonia para satisfazer.",
  "Por que o ladrão de pizza nunca foi pego? Ele sempre estava um passo à frente, comendo a evidência!",
  "Como chamam o boi que toca na banda? Um baterista bovino, que marca o ritmo com estilo!",
  "Por que o elefante evitava computadores? Porque o mouse sempre fazia ele se lembrar de algo pequeno demais.",
  "Qual é a piada favorita do marceneiro? A serra que faz todo mundo cortar o papo.",
  "O que o zero disse ao oito? 'Você emagreceu ou está usando cinto novo?'",
  "Por que a bicicleta decidiu tirar um cochilo? Estava cansada de pedalar em círculos.",
  "Por que o espelho estava em crise? Ele refletia demais sobre o passado.",
  "Por que o caderno estava melancólico? Suas páginas em branco aguardavam grandes histórias.",
  "Qual é o cúmulo da confusão? Perder o fio da meada num novelo desfiado.",
  "Por que o tomate nunca vai ao banco? Ele não quer correr o risco de ser esmagado nas finanças.",
  "O que a impressora disse ao papel? 'Estamos fazendo história juntos!'",
  "Por que a vaca não usa gravata? Porque o colarinho natural dela é pura classe!",
  "O que o pato disse à pata? 'Com você, minha vida está completa, quack!'",
  "Por que o balde é o funcionário do mês? Ele está sempre cheio de boas ideias!",
  "O que a ovelha disse antes do corte? 'Espero que minha lã inspire novos estilos!'",
  "Por que o cachorro foi estudar línguas? Para aprender a latir em várias culturas.",
  "Por que o pássaro não vai ao médico? Ele prefere se sentir leve como uma pluma.",
  "O que o lápis disse ao caderno? 'Vamos juntos criar novas histórias, uma página de cada vez.'",
  "Por que a lâmpada foi promovida? Porque ela iluminava as melhores ideias!",
  "O que a chave disse ao cadeado? 'Estamos juntos nesta jornada de abrir portas.'",
  "Por que o relógio está sempre feliz? Porque ele vive em tempo constante de alegria!",
  "O que o papel disse à caneta? 'Vamos juntos escrever um novo capítulo.'",
  "Por que o lápis foi ao médico? Estava sentindo seu grafite se desgastar com o tempo.",
  "Qual é o contrário de volátil? Algo que se mantém firme como uma rocha!",
  "O que o termômetro disse ao médico? 'Estou sempre à altura da situação!'",
  "Por que o macarrão evita o banco? Ele não quer ficar enrolado em dívidas.",
  "O que o pão disse à manteiga? 'Você torna meu dia mais saboroso!'",
  "Por que a máquina de lavar estava irritada? Estava cheia de problemas para resolver.",
  "O que o chinelo disse ao pé? 'Estou aqui para te apoiar em cada passo.'",
  "Por que o lápis não conta piadas? Ele sempre apaga o melhor final.",
  "O que a nota musical disse à partitura? 'Estamos juntos na harmonia perfeita.'",
  "Por que o feijão estava se sentindo mal? Ele estava sob pressão.",
  "O que o calendário disse ao relógio? 'Vamos sincronizar nossas vidas.'",
  "Por que o chocolate procurou um terapeuta? Ele estava derretendo de tanto stress.",
  "O que a luva disse à mão? 'Estou aqui para te proteger em todas as situações.'",
  "Por que o guarda-chuva não compartilha segredos? Ele é extremamente reservado.",
  "O que o celular disse ao carregador? 'Você me completa, sempre.'",
  "Por que a faca nunca discutiu com o garfo? Eles sempre apontam na mesma direção.",
  "O que o caderno disse à caneta? 'Vamos escrever nossa história, um capítulo de cada vez.'",
  "Por que o gato evita o cinema? Ele teme ser pego numa trama felina.",
  "O que o pinguim disse à geladeira? 'Você me mantém sempre frio e calculista.'",
  "Por que o sapato procurou ajuda? Estava cansado de pisar nos mesmos problemas.",
  "O que a toalha disse à água? 'Estou pronta para te abraçar em cada gota.'",
  "Por que o livro de matemática estava triste? Ele tinha problemas sem solução.",
  "O que a chave disse ao cadeado? 'Somos inseparáveis, em qualquer situação.'",
  "Por que o quadro sempre chamava atenção? Ele sabia enquadrar qualquer momento.",
  "O que o lápis disse ao apontador? 'Você me faz afiado e preparado para qualquer desafio.'",
  "Por que o armário se isolou? Estava cheio de assuntos para resolver por dentro.",
  "O que a cadeira disse à mesa? 'Juntos, apoiamos muitas ideias.'",
  "Por que a cortina procurou ajuda? Estava cansada de carregar o peso do drama.",
  "O que o sorvete disse à colher? 'Você me faz derreter de amor.'",
  "Por que a melancia evitou o médico? Estava cheia de sementes de otimismo.",
  "O que o travesseiro disse ao lençol? 'Vamos sonhar grandes sonhos juntos.'",
  "Por que a parede procurou ajuda? Estava sentindo o peso das expectativas.",
  "O que o ventilador disse ao calor? 'Vou mandar você para longe!'",
  "Por que o relógio nunca briga com o tempo? Eles estão sempre em harmonia.",
  "O que a maçaneta disse à porta? 'Vamos abrir novas oportunidades juntos!'",
  "Por que a chave de fenda foi promovida? Ela sabia como resolver qualquer situação.",
  "O que a janela disse à cortina? 'Juntos, vamos revelar novas vistas.'",
  "Por que o violão foi ao médico? Estava com as cordas soltas de tanto tocar.",
  "O que a faca disse à tábua de corte? 'Juntos, somos imbatíveis na cozinha.'",
  "Por que a garrafa de água estava calma? Ela estava cheia de paz interior.",
  "O que o lápis disse à borracha? 'Você me dá uma segunda chance.'",
  "Por que o biscoito não procurou ajuda? Já estava quebrado, mas ainda saboroso.",
  "O que o telefone disse ao fone de ouvido? 'Estamos sempre conectados, onde quer que vá.'",
  "Por que o patinete estava sempre feliz? Ele adorava a liberdade de rodar por aí.",
  "O que o café disse à xícara? 'Eu sou a energia que você precisa.'",
  "Por que o papel higiênico nunca discutiu? Ele sabia como resolver qualquer situação calmamente.",
  "O que o chaveiro disse às chaves? 'Estamos juntos na bagunça do dia a dia!'",
];

const creativePhrases = [
  "Aproveite esta pausa!",
  "Sorria, alguém pensa em você!",
  "Hora de uma nova ideia!",
  "Quem não arrisca, não petisca!",
  "As melhores ideias surgem nas horas mais inesperadas!",
  "Seja a mudança que você quer ver no mundo!",
  "Pense fora da caixinha!",
  "Deixe sua criatividade voar alto!",
  "Tudo o que você precisa está dentro de você.",
  "Transforme suas ideias em realidade.",
  "Explore o desconhecido e descubra novas possibilidades.",
  "A inspiração está ao seu redor.",
  "Dê asas à sua imaginação.",
  "O impossível é apenas o que ainda não foi tentado.",
  "Cada dia é uma nova oportunidade para criar.",
  "Você é o arquiteto dos seus sonhos.",
  "A criatividade é a inteligência se divertindo.",
  "Pinte sua vida com as cores dos seus sonhos.",
  "A arte de criar é a arte de viver.",
  "Deixe sua marca no mundo.",
  "O mundo é o seu palco, brilhe!",
  "Seja ousado, seja criativo.",
  "A inovação começa com uma ideia simples.",
  "Transforme problemas em oportunidades criativas.",
  "A magia acontece quando você acredita.",
  "Crie algo que inspire os outros.",
  "Deixe sua criatividade fluir livremente.",
  "Acredite na sua capacidade de criar algo incrível.",
  "O mundo é cheio de possibilidades, explore-as!",
  "Cada ideia é uma nova aventura.",
  "Desafie-se a pensar de maneira diferente.",
  "A imaginação é o início de todas as realizações.",
  "A criatividade não tem limites.",
  "Pense grande, sonhe alto.",
  "A arte de criar é a arte de ser único.",
  "Inspire-se e inspire os outros.",
  "O futuro pertence aos criativos.",
  "A criatividade é a chave para o sucesso.",
  "Seja a mudança que você deseja ver no mundo.",
  "Crie o que você deseja ver no mundo.",
  "A inovação nasce da curiosidade.",
  "Acredite na sua capacidade de fazer a diferença.",
  "Pinte o mundo com as cores dos seus sonhos.",
  "O poder da criatividade está nas suas mãos.",
  "Crie algo que seja digno de ser lembrado.",
  "A criatividade é a linguagem universal.",
  "O mundo precisa da sua criatividade.",
  "A imaginação é o único limite.",
  "Crie o seu próprio caminho.",
  "A criatividade é a alma da inovação.",
  "Seja criativo em tudo o que você faz.",
  "A imaginação é o primeiro passo para a criação.",
  "O poder da criatividade é ilimitado.",
  "Crie o que faz seu coração cantar.",
  "A criatividade é o segredo do sucesso.",
  "Transforme ideias em ações.",
  "A arte de criar é a arte de se expressar.",
  "A imaginação é a janela para o futuro.",
  "A criatividade é a chama que acende a inovação.",
  "O mundo precisa da sua visão única.",
  "Seja corajoso o suficiente para ser criativo.",
  "Crie algo que traga alegria ao mundo.",
  "A imaginação é o combustível da criatividade.",
  "A criatividade é a chave para a mudança.",
  "Pinte o mundo com a paleta dos seus sonhos.",
  "Acredite na sua capacidade de transformar o mundo.",
  "A criatividade é a essência da inovação.",
  "Crie algo que inspire os outros a sonhar.",
  "A imaginação é o início de toda criação.",
  "A criatividade é a chave para a felicidade.",
  "Acredite no poder da sua imaginação.",
  "Crie o que faz o seu coração bater mais forte.",
  "A arte de criar é a arte de viver com paixão.",
  "Pense fora da caixa e crie algo extraordinário.",
  "A criatividade é a chave para o futuro.",
  "Crie algo que faça o mundo sorrir.",
  "A imaginação é o combustível da inovação.",
  "A criatividade é a chave para a realização pessoal.",
  "Acredite na sua capacidade de criar o impossível.",
  "Pinte a vida com as cores da sua imaginação.",
  "A arte de criar é a arte de transformar sonhos em realidade.",
  "Crie algo que toque o coração das pessoas.",
  "A criatividade é a chave para a verdadeira felicidade.",
  "Seja ousado o suficiente para ser criativo.",
  "Crie algo que inspire os outros a seguir seus sonhos.",
  "A imaginação é o primeiro passo para a grandeza.",
  "A criatividade é o motor da mudança.",
  "Pinte o mundo com a sua visão única.",
  "Acredite na sua capacidade de transformar o mundo para melhor.",
  "A criatividade é a chave para o sucesso duradouro.",
];

export function getRandomPhrase() {
  const currentHour = new Date().getHours();

  if (currentHour % 3 === 0) {
    return motivationalPhrases[
      Math.floor(Math.random() * motivationalPhrases.length)
    ];
  } else if (currentHour % 3 === 1) {
    return jokes[Math.floor(Math.random() * jokes.length)];
  } else {
    return creativePhrases[Math.floor(Math.random() * creativePhrases.length)];
  }
}
